version: '3.8'

services:
  backend:
    build:
      context: ./docker/apache-php
    container_name: backend
    volumes:
      - ./backend:/var/www/html
    ports:
      - "${PHP_HTTP_PORT}:80"
    depends_on:
      - database
    networks:
      - app-network
    env_file:
      - .env

  database:
    image: mysql:5.7
    container_name: database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_HOST: '%'
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "${MYSQL_PORT}:3306"
    networks:
      - app-network

  frontend:
    image: node:20
    container_name: frontend
    working_dir: /app
    command: sh -c "npm install && npm run dev"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "${FRONTEND_PORT}:5173"
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
